# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 05:26
from __future__ import unicode_literals

import cv.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('photo', models.ImageField(blank=True, height_field='height', null=True, upload_to=cv.models.upload, width_field='width')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('about_you', models.TextField(max_length=250)),
                ('address', models.TextField(max_length=250)),
                ('hobbies_and_intrests', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('X Secondary', 'Secondary'), ('XII Senior Secondary', 'XII Senior Secondary'), ('Diploma', 'Diploma'), ('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('PHD', 'PHD')], max_length=30)),
                ('instute_name', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='cv.CV')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.CV')),
            ],
        ),
        migrations.CreateModel(
            name='WE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('years', models.IntegerField()),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='cv.CV')),
            ],
        ),
        migrations.AddField(
            model_name='achieve',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='cv.CV'),
        ),
    ]
