# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='we',
            name='years',
            field=models.CharField(max_length=10),
        ),
    ]
